const LOAD_MENU = 'LOAD_MENU';
const GET_ACTIVE_CATEGORY = 'GET_ACTIVE_CATEGORY';
const GET_ITEM_CARDS = 'GET_ITEM_CARDS'
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export { LOAD_MENU, ADD_TO_CART, REMOVE_FROM_CART, GET_ACTIVE_CATEGORY, GET_ITEM_CARDS};